### ISSUE TITLE
AttributeError: module 'streamlink.plugin.api.validate' has no attribute 'text'

### ISSUE THREAD

**Issue by glottisfaun0000** [streamlink-plugins/streamlink-plugins#6]
```AttributeError: module 'streamlink.plugin.api.validate' has no attribute 'text'```

i've seen this error for a couple months at least, but I think streamlink 6.0.0 broke it for good. chaturbate.py is not working on the latest streamlink version.

**Comment by odnar-dev** [comment]
please use the latest plugins version from the main branch, this has been fixed for [Chaturbate](https://raw.githubusercontent.com/community-plugins/streamlink-plugins/main/plugins/chaturbate.py)

**Comment by glottisfaun0000** [comment]
thanks for that- my problem was weird. this was still happening with the most recent `chaturbate.py`, but what i figured out was that streamlink 6.0.0 was killing the process when it read the `validate.text` in _other_ plugins (hanime, camsoda) for some reason. so with just `generic.py` and `chaturbate.py` in my plugins folder, it's working. leaving this info for anyone else who has the issue.
